name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: test -z $(gofmt -l .)
      - run: go test ./...
      - run: go build ./cmd/gokart.go
